[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "house_price_prediction"
version = "0.0.0"
description = "House price prediction pipeline"


packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
joblib = "*"
matplotlib = "*"
mlflow = "*"
numpy = "*"
pandas = "*"
scikit-learn = "*"
seaborn = "*"
xgboost = "*"
ruff = "*"
pytest = "*"
statsmodels = "^0.14.6"
pytest-cov = "*"


[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "W", "I"]  
ignore = ["E501"]

[tool.ruff.lint.isort]
known-first-party = ["src"]   

# TODO: add new script folders to include when you add stages
# e.g. include = ["scripts/", "src/"]


# ─── Coverage ─────────────────────────────────────────────────────────────────
[tool.coverage.run]
source = ["src"]
omit = [
    "tests/*",
    "**/__init__.py",
    "src/models/*",
    "src/visualization/*"
]

# TODO: add new source folders here as you add stages
# e.g. source = ["scripts", "src/training", "src/evaluation"]

[tool.coverage.report]
show_missing = true
skip_empty   = true


