[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "house_price_prediction"
version = "0.0.0"
description = "House price prediction pipeline"


packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "^3.12"
joblib = "*"
matplotlib = "*"
mlflow = "*"
numpy = "*"
pandas = "*"
scikit-learn = "*"
seaborn = "*"
xgboost = "*"


[tool.poetry.group.dev.dependencies]
pytest = "*"
ruff = "*"